Repository rust-windowing/winit, pull requests merged in 2020-09, with the labels that each got.

#1708 Android: bump ndk versions
  CHANGELOG.md
  Cargo.toml
  README.md
Labels: platform: Android, status: needs review

#1703 Fix view frame in portrait when starting iOS app in landscape
  CHANGELOG.md
  src/platform_impl/ios/ffi.rs
  src/platform_impl/ios/view.rs
Labels: platform: iOS, status: needs review

#1653 Update SCTK to 0.11.0
  CHANGELOG.md
  Cargo.toml
  src/platform/desktop.rs
  src/platform/unix.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/env.rs
  src/platform_impl/linux/wayland/event_loop.rs
  src/platform_impl/linux/wayland/event_loop/mod.rs
  src/platform_impl/linux/wayland/event_loop/proxy.rs
  src/platform_impl/linux/wayland/event_loop/sink.rs
  src/platform_impl/linux/wayland/event_loop/state.rs
  src/platform_impl/linux/wayland/keyboard.rs
  src/platform_impl/linux/wayland/mod.rs
  src/platform_impl/linux/wayland/output.rs
  src/platform_impl/linux/wayland/pointer.rs
  src/platform_impl/linux/wayland/seat/keyboard/handlers.rs
  src/platform_impl/linux/wayland/seat/keyboard/keymap.rs
  src/platform_impl/linux/wayland/seat/keyboard/mod.rs
  src/platform_impl/linux/wayland/seat/mod.rs
  src/platform_impl/linux/wayland/seat/pointer/data.rs
  src/platform_impl/linux/wayland/seat/pointer/handlers.rs
  src/platform_impl/linux/wayland/seat/pointer/mod.rs
  src/platform_impl/linux/wayland/seat/text_input/handlers.rs
  src/platform_impl/linux/wayland/seat/text_input/mod.rs
  src/platform_impl/linux/wayland/seat/touch/handlers.rs
  src/platform_impl/linux/wayland/seat/touch/mod.rs
  src/platform_impl/linux/wayland/touch.rs
  src/platform_impl/linux/wayland/window.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/wayland/window/shim.rs
  src/window.rs
Labels: status: needs review
