Repository rust-windowing/winit, pull requests merged in 2023-09, with the labels that each got.

#3071 Slightly reduce number of `cfg`s
  src/event.rs
  src/event_loop.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/ios/event_loop.rs
  src/platform_impl/ios/window.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/event_loop/mod.rs
  src/platform_impl/linux/wayland/output.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/x11/event_processor.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/linux/x11/monitor.rs
  src/platform_impl/linux/x11/util/icon.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/event_loop.rs
  src/platform_impl/orbital/event_loop.rs
  src/platform_impl/orbital/window.rs
  src/platform_impl/web/window.rs
  src/window.rs
Labels: S - maintenance

#3081 Web: Remove `T` from `EventLoopTargetWindow`
  src/platform_impl/web/event_loop/mod.rs
  src/platform_impl/web/event_loop/proxy.rs
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/canvas.rs
Labels: DS - wasm

#3058 Allow the user to force X11 under Wayland
  CHANGELOG.md
  src/platform_impl/linux/mod.rs
Labels: DS - x11

#3084 Add option to use `Window.requestIdleCallback()` for `ControlFlow::Poll`
  CHANGELOG.md
  src/platform/web.rs
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/schedule.rs
Labels: DS - wasm

#3089 Rename `PollType` to `PollStrategy`
  CHANGELOG.md
  src/platform/web.rs
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/schedule.rs
Labels: DS - wasm

#3097 Ignore duplicate dependencies in CI
  Cargo.toml
  deny.toml
Labels: DS - macos

#3098 Install `cargo-apk` with the stable toolchain
  .github/workflows/ci.yml
Labels: DS - android

#3091 Fix WaitUntil on X11
  CHANGELOG.md
  src/platform_impl/linux/x11/mod.rs
Labels: DS - x11

#3020 Pass force on touch events on android
  CHANGELOG.md
  src/event.rs
  src/platform_impl/android/mod.rs
Labels: DS - android

#3115 Fix transparet windows in X11
  src/platform_impl/linux/x11/window.rs
  src/window.rs
Labels: DS - x11

#3070 Windows: Add `#[deny(unsafe_op_in_unsafe_fn)]`
  src/platform_impl/windows/dpi.rs
  src/platform_impl/windows/drop_handler.rs
  src/platform_impl/windows/event_loop.rs
  src/platform_impl/windows/event_loop/runner.rs
  src/platform_impl/windows/ime.rs
  src/platform_impl/windows/mod.rs
  src/platform_impl/windows/monitor.rs
  src/platform_impl/windows/window.rs
Labels: DS - windows, S - maintenance

#3121 X11: Add `#[deny(unsafe_op_in_unsafe_fn)]`
  src/event.rs
  src/lib.rs
  src/platform_impl/ios/uikit/mod.rs
  src/platform_impl/linux/common/xkb_state.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/x11/event_processor.rs
  src/platform_impl/linux/x11/ime/callbacks.rs
  src/platform_impl/linux/x11/ime/context.rs
  src/platform_impl/linux/x11/ime/inner.rs
  src/platform_impl/linux/x11/ime/input_method.rs
  src/platform_impl/macos/mod.rs
  src/platform_impl/windows/mod.rs
  src/window.rs
Labels: DS - x11, S - maintenance
