Repository rust-windowing/winit, pull requests merged in 2023-12, with the labels that each got.

#3264 On Wayland, make `wl_subcompositor` protocol optional
  CHANGELOG.md
  src/platform_impl/linux/wayland/state.rs
  src/platform_impl/linux/wayland/window/state.rs
Labels: DS - wayland

#3261 On Windows, fix `set_fullscreen` early return for `Fullscreen::Borderless(None)`
  CHANGELOG.md
  src/platform_impl/windows/window.rs
Labels: DS - windows

#3242 Web: remove queuing fullscreen request
  CHANGELOG.md
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/web_sys/fullscreen.rs
  src/platform_impl/web/web_sys/pointer.rs
  src/window.rs
Labels: DS - wasm

#3269 On Web, fix setting cursor icon overriding cursor visibility
  CHANGELOG.md
  src/platform_impl/web/cursor.rs
  src/platform_impl/web/window.rs
Labels: DS - wasm

#3271 windows set ime area not work
  CHANGELOG.md
  src/platform_impl/windows/ime.rs
Labels: DS - windows

#3280 On Web, correctly mark breaking changes in the changelog
  CHANGELOG.md
Labels: DS - wasm

#3282 On Web, fix context menu not being disabled by `with_prevent_default(true)`
  CHANGELOG.md
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/canvas.rs
Labels: DS - wasm

#3274 Fix some doc nits
  src/window.rs
Labels: DS - ios, DS - wasm

#3276 Allow custom cursor caching
  Cargo.toml
  examples/custom_cursors.rs
  src/cursor.rs
  src/platform/web.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/ios/mod.rs
  src/platform_impl/ios/window.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/wayland/window/state.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/mod.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/orbital/mod.rs
  src/platform_impl/orbital/window.rs
  src/platform_impl/web/async/channel.rs
  src/platform_impl/web/async/dispatcher.rs
  src/platform_impl/web/async/mod.rs
  src/platform_impl/web/cursor.rs
  src/platform_impl/web/mod.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/mod.rs
  src/platform_impl/windows/window.rs
  src/window.rs
  tests/send_objects.rs
  tests/sync_object.rs
Labels: S - api, DS - wasm

#3270 On Web, use the new `WebCanvasWindowHandle`
  CHANGELOG.md
  src/platform_impl/ios/window.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/web_sys/pointer.rs
  src/platform_impl/web/window.rs
  src/window.rs
Labels: DS - wasm

#3288 Window handle: Return an error when not on main thread on macOS and iOS
  CHANGELOG.md
  src/platform_impl/ios/window.rs
  src/platform_impl/macos/window.rs
  src/window.rs
Labels: DS - macos, DS - ios

#3289 Fix changelog
  CHANGELOG.md
Labels: DS - wasm

#3290 Use `std::cell::OnceCell`
  src/platform_impl/web/web_sys/event.rs
  src/platform_impl/web/web_sys/fullscreen.rs
  src/platform_impl/web/web_sys/schedule.rs
Labels: DS - wasm

#3292 Custom cursor improvements
  src/cursor.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/ios/window.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/types/cursor.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/wayland/window/state.rs
  src/platform_impl/linux/x11/util/cursor.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/mod.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/orbital/window.rs
  src/platform_impl/web/cursor.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/icon.rs
  src/platform_impl/windows/mod.rs
  src/platform_impl/windows/window.rs
  src/window.rs
Labels: S - maintenance

#3291 MacOS: cache custom cursor
  src/platform_impl/macos/cursor.rs
  src/platform_impl/macos/mod.rs
  src/platform_impl/macos/window.rs
Labels: DS - macos

#3256 Update `objc2` and `icrate` versions
  Cargo.toml
  src/platform_impl/ios/monitor.rs
  src/platform_impl/ios/view.rs
  src/platform_impl/ios/window.rs
  src/platform_impl/macos/app.rs
  src/platform_impl/macos/app_delegate.rs
  src/platform_impl/macos/appkit/cursor.rs
  src/platform_impl/macos/appkit/screen.rs
  src/platform_impl/macos/menu.rs
  src/platform_impl/macos/view.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/macos/window_delegate.rs
Labels: DS - macos, DS - ios, S - maintenance

#2982 Partially replace custom AppKit bindings with icrate's autogenerated bindings
  Cargo.toml
  src/platform/macos.rs
  src/platform_impl/macos/app.rs
  src/platform_impl/macos/app_state.rs
  src/platform_impl/macos/appkit/appearance.rs
  src/platform_impl/macos/appkit/application.rs
  src/platform_impl/macos/appkit/bitmap_image_rep.rs
  src/platform_impl/macos/appkit/button.rs
  src/platform_impl/macos/appkit/color.rs
  src/platform_impl/macos/appkit/control.rs
  src/platform_impl/macos/appkit/cursor.rs
  src/platform_impl/macos/appkit/event.rs
  src/platform_impl/macos/appkit/image.rs
  src/platform_impl/macos/appkit/menu.rs
  src/platform_impl/macos/appkit/menu_item.rs
  src/platform_impl/macos/appkit/mod.rs
  src/platform_impl/macos/appkit/pasteboard.rs
  src/platform_impl/macos/appkit/responder.rs
  src/platform_impl/macos/appkit/screen.rs
  src/platform_impl/macos/appkit/text_input_client.rs
  src/platform_impl/macos/appkit/text_input_context.rs
  src/platform_impl/macos/appkit/version.rs
  src/platform_impl/macos/appkit/view.rs
  src/platform_impl/macos/appkit/window.rs
  src/platform_impl/macos/cursor.rs
  src/platform_impl/macos/event.rs
  src/platform_impl/macos/event_loop.rs
  src/platform_impl/macos/menu.rs
  src/platform_impl/macos/monitor.rs
  src/platform_impl/macos/view.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/macos/window_delegate.rs
Labels: DS - macos, S - maintenance

#3296 Replace remaining AppKit bindings with `icrate`'s
  src/platform/pump_events.rs
  src/platform_impl/macos/app.rs
  src/platform_impl/macos/app_delegate.rs
  src/platform_impl/macos/app_state.rs
  src/platform_impl/macos/appkit/application.rs
  src/platform_impl/macos/appkit/mod.rs
  src/platform_impl/macos/appkit/tab_group.rs
  src/platform_impl/macos/appkit/window.rs
  src/platform_impl/macos/event_loop.rs
  src/platform_impl/macos/ffi.rs
  src/platform_impl/macos/menu.rs
  src/platform_impl/macos/mod.rs
  src/platform_impl/macos/observer.rs
  src/platform_impl/macos/view.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/macos/window_delegate.rs
Labels: DS - macos, S - maintenance

#3302 macOS: Clean up coordinate system calculations
  clippy.toml
  examples/fullscreen.rs
  examples/multithreaded.rs
  src/platform_impl/ios/monitor.rs
  src/platform_impl/macos/monitor.rs
  src/platform_impl/macos/util.rs
  src/platform_impl/macos/view.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/macos/window_delegate.rs
Labels: DS - macos, S - maintenance

#3295 (Try to) simplify x11's available_monitors()
  src/platform_impl/linux/x11/monitor.rs
Labels: DS - x11, S - maintenance

#3312 Web documentation improvements
  src/cursor.rs
  src/platform/web.rs
  src/window.rs
Labels: S - docs, DS - wasm

#3308 Merge `Window::set_cursor_icon()` and `Window::set_custom_cursor()`
  CHANGELOG.md
  examples/cursor.rs
  examples/custom_cursors.rs
  examples/multithreaded.rs
  examples/window_drag_resize.rs
  src/cursor.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/ios/window.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/orbital/window.rs
  src/platform_impl/web/cursor.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/window.rs
  src/window.rs
Labels: S - api

#3314 Remove wrong documentation on `EventLoop::run()`
  src/event_loop.rs
Labels: S - docs

#3310 Remove `extern crate` statements
  src/dpi.rs
  src/event.rs
  src/keyboard.rs
  src/lib.rs
  src/platform/ios.rs
  src/platform/macos.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/ios/event_loop.rs
  src/platform_impl/ios/uikit/view_controller.rs
  src/platform_impl/ios/window.rs
  src/platform_impl/linux/common/xkb_state.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/event_loop/mod.rs
  src/platform_impl/linux/wayland/state.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/x11/ime/context.rs
  src/platform_impl/linux/x11/ime/mod.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/linux/x11/util/hint.rs
  src/platform_impl/linux/x11/util/input.rs
  src/platform_impl/linux/x11/util/randr.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/app_state.rs
  src/platform_impl/macos/cursor.rs
  src/platform_impl/macos/util.rs
  src/platform_impl/macos/view.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/orbital/event_loop.rs
  src/platform_impl/web/web_sys/event.rs
  src/platform_impl/web/web_sys/resize_scaling.rs
  src/platform_impl/windows/drop_handler.rs
  src/platform_impl/windows/keyboard.rs
  src/platform_impl/windows/keyboard_layout.rs
  src/platform_impl/windows/window.rs
  src/platform_impl/windows/window_state.rs
  src/window.rs
Labels: S - enhancement

#3307 On Web, add `Window::(set_)prevent_default()`
  CHANGELOG.md
  src/platform/web.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/web_sys/pointer.rs
  src/platform_impl/web/window.rs
Labels: DS - wasm

#3320 Make `canvas` in `WindowBuilder` safe
  src/platform/web.rs
  src/platform_impl/web/async/dispatcher.rs
  src/platform_impl/web/async/waker.rs
  src/platform_impl/web/async/wrapper.rs
  src/platform_impl/web/cursor.rs
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/main_thread.rs
  src/platform_impl/web/mod.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/window.rs
Labels: DS - wasm

#3321 Web: improve custom cursor loading
  src/platform_impl/web/cursor.rs
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/window.rs
Labels: DS - wasm

#3309 Reload Xft database on DPI change
  src/platform_impl/linux/x11/event_processor.rs
  src/platform_impl/linux/x11/xdisplay.rs
Labels: DS - x11

#3324 MacOS: check if cursor changed before applying
  src/platform_impl/macos/view.rs
  src/platform_impl/macos/window.rs
Labels: DS - macos

#3319 Add `WindowBuilder::with_cursor()`
  CHANGELOG.md
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/window.rs
  src/window.rs
Labels: DS - macos, DS - windows, DS - x11, DS - wayland, S - api, DS - wasm

#3303 Remove unsound `SendSyncWrapper`
  CHANGELOG.md
  src/lib.rs
  src/platform_impl/ios/view.rs
  src/platform_impl/ios/window.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/monitor.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/window.rs
  src/window.rs
Labels: B - bug, DS - macos

#3328 Rename `VideoMode` to `VideoModeHandle`
  CHANGELOG.md
  src/monitor.rs
  src/platform/ios.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/ios/mod.rs
  src/platform_impl/ios/monitor.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/mod.rs
  src/platform_impl/linux/wayland/output.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/linux/x11/monitor.rs
  src/platform_impl/linux/x11/util/randr.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/macos/mod.rs
  src/platform_impl/macos/monitor.rs
  src/platform_impl/macos/window.rs
  src/platform_impl/mod.rs
  src/platform_impl/orbital/mod.rs
  src/platform_impl/web/mod.rs
  src/platform_impl/web/monitor.rs
  src/platform_impl/windows/mod.rs
  src/platform_impl/windows/monitor.rs
  src/window.rs
Labels: S - api

#3329 Add deprecated `Window::set_cursor_icon()`
  src/window.rs
Labels: S - api
