Repository rust-windowing/winit, pull requests merged in 2023-05, with the labels that each got.

#2778 Don't change the internal canvas size
  CHANGELOG.md
  src/platform_impl/web/web_sys/mod.rs
Labels: DS - wasm

#2732 On Web, wake event loop on `request_redraw()`
  CHANGELOG.md
  src/platform_impl/web/event_loop/runner.rs
Labels: DS - wasm

#2815 Fix window set_theme doc string
  src/window.rs
Labels: S - docs, C - waiting on author

#2700 Renamed `DeviceEventFilter` to `DeviceEvents`
  CHANGELOG.md
  examples/window_buttons.rs
  examples/window_debug.rs
  src/event_loop.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/x11/event_processor.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/windows/event_loop.rs
  src/platform_impl/windows/raw_input.rs
Labels: DS - x11, I - BREAKING CHANGE

#2751 On Web, fix async `Window::set_fullscreen`
  CHANGELOG.md
  Cargo.toml
  src/platform_impl/web/web_sys/canvas.rs
  src/window.rs
Labels: DS - wasm
