Repository rust-windowing/winit, pull requests merged in 2024-12, with the labels that each got.

#4025 Fix Clippy lints
  src/platform_impl/apple/appkit/view.rs
  src/platform_impl/linux/common/xkb/mod.rs
  src/platform_impl/linux/x11/activation.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/linux/x11/monitor.rs
  src/platform_impl/linux/x11/util/memory.rs
  src/platform_impl/orbital/mod.rs
  src/platform_impl/windows/event_loop.rs
  src/platform_impl/windows/window.rs
Labels: S - maintenance

#4021 Linux: Align scancode conversions with Firefox
  src/changelog/unreleased.md
  src/platform_impl/linux/common/xkb/keymap.rs
Labels: S - enhancement, DS - x11, DS - wayland

#3912 AppKit/UIKit: Do not emit default state events upon window creation
  src/changelog/unreleased.md
  src/event.rs
  src/platform_impl/apple/appkit/window_delegate.rs
  src/platform_impl/apple/uikit/window.rs
Labels: B - bug, DS - macos, DS - ios, S - platform parity

#4028 macOS: Fix safe area on macOS 10.14 and below
  src/platform_impl/apple/appkit/window_delegate.rs
Labels: B - bug, DS - macos

#4027 macOS: Fix surface position
  src/platform_impl/apple/appkit/window_delegate.rs
Labels: B - bug, DS - macos

#4019 macOS: Align scancode conversions with Chromium and Firefox
  src/changelog/unreleased.md
  src/platform_impl/apple/appkit/event.rs
Labels: B - bug, S - enhancement, DS - macos

#3913 macOS: Avoid redundant initial resize event
  src/changelog/unreleased.md
  src/platform_impl/apple/appkit/view.rs
  src/platform_impl/apple/appkit/window_delegate.rs
Labels: B - bug, DS - macos

#4024 macOS: Fix crash when pressing Caps Lock
  src/changelog/unreleased.md
  src/platform_impl/apple/appkit/event.rs
  src/platform_impl/apple/appkit/view.rs
Labels: DS - macos, B - crash

#4013 Fix `MonitorHandle` `PartialEq` and `Hash` on iOS
  src/changelog/unreleased.md
  src/platform_impl/apple/uikit/monitor.rs
Labels: B - bug, DS - ios

#3905 iOS: Never queue application-level events
  src/changelog/unreleased.md
  src/platform_impl/apple/event_handler.rs
  src/platform_impl/apple/uikit/app_state.rs
  src/platform_impl/apple/uikit/event_loop.rs
  src/platform_impl/apple/uikit/view.rs
  src/platform_impl/apple/uikit/window.rs
Labels: DS - ios, S - maintenance

#3479 Remove feature descriptions in `FEATURES.md`
  .github/PULL_REQUEST_TEMPLATE.md
  FEATURES.md
  src/event.rs
  src/monitor.rs
  src/window.rs
Labels: S - docs, S - maintenance

#3991 Update `smol_str`
  Cargo.toml
  src/changelog/unreleased.md
Labels: S - api, dependencies

#4016 Show less of the unstable docs in the README
  README.md
Labels: S - docs

#4033 macOS: Fix selector response checking for undocumented cursors
  src/changelog/unreleased.md
  src/platform_impl/apple/appkit/cursor.rs
Labels: B - bug, DS - macos

#4035 Implement ability to make non-activating window on macOS
  Cargo.toml
  src/changelog/unreleased.md
  src/platform/macos.rs
  src/platform_impl/apple/appkit/view.rs
  src/platform_impl/apple/appkit/window.rs
  src/platform_impl/apple/appkit/window_delegate.rs
Labels: S - enhancement, DS - macos
