Repository rust-windowing/winit, pull requests merged in 2024-09, with the labels that each got.

#3889 Rename "inner size" to "surface size"
  examples/child_window.rs
  examples/run_on_demand.rs
  examples/util/fill.rs
  examples/window.rs
  examples/x11_embed.rs
  src/changelog/unreleased.md
  src/event.rs
  src/monitor.rs
  src/platform/web.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/apple/appkit/view.rs
  src/platform_impl/apple/appkit/window.rs
  src/platform_impl/apple/appkit/window_delegate.rs
  src/platform_impl/apple/uikit/app_state.rs
  src/platform_impl/apple/uikit/view.rs
  src/platform_impl/apple/uikit/window.rs
  src/platform_impl/linux/wayland/event_loop/mod.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/wayland/window/state.rs
  src/platform_impl/linux/x11/event_processor.rs
  src/platform_impl/linux/x11/util/geometry.rs
  src/platform_impl/linux/x11/window.rs
  src/platform_impl/orbital/event_loop.rs
  src/platform_impl/orbital/window.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/event_loop.rs
  src/platform_impl/windows/event_loop/runner.rs
  src/platform_impl/windows/window.rs
  src/platform_impl/windows/window_state.rs
  src/window.rs
Labels: S - api, S - docs, I - BREAKING CHANGE

#3904 Enable drawing on iOS/UIKit in examples
  Cargo.toml
  examples/window.rs
Labels: S - docs, DS - ios, dependencies

#3914 macOS: Fix move event sometimes being triggered on resize
  src/changelog/unreleased.md
  src/platform_impl/apple/appkit/window_delegate.rs
Labels: B - bug, DS - macos

#3795 Replace `WindowId` `From/Into` `u64` with `WindowId::into_raw()` and `from_raw()`
  src/changelog/unreleased.md
  src/platform_impl/android/mod.rs
  src/platform_impl/apple/appkit/window.rs
  src/platform_impl/apple/uikit/window.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/orbital/mod.rs
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/mod.rs
  src/window.rs
Labels: S - api, C - nominated

#3864 Remove `dummy()` from `WindowId` and `DeviceId` and use `Option<DeviceId>`
  examples/window.rs
  src/application.rs
  src/changelog/unreleased.md
  src/event.rs
  src/platform_impl/android/mod.rs
  src/platform_impl/apple/appkit/app.rs
  src/platform_impl/apple/appkit/mod.rs
  src/platform_impl/apple/appkit/view.rs
  src/platform_impl/apple/appkit/window.rs
  src/platform_impl/apple/uikit/mod.rs
  src/platform_impl/apple/uikit/view.rs
  src/platform_impl/apple/uikit/window.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/event_loop/mod.rs
  src/platform_impl/linux/wayland/event_loop/sink.rs
  src/platform_impl/linux/wayland/mod.rs
  src/platform_impl/linux/wayland/seat/keyboard/mod.rs
  src/platform_impl/linux/wayland/seat/pointer/mod.rs
  src/platform_impl/linux/wayland/seat/pointer/relative_pointer.rs
  src/platform_impl/linux/wayland/seat/touch/mod.rs
  src/platform_impl/linux/x11/event_processor.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/linux/x11/util/input.rs
  src/platform_impl/orbital/event_loop.rs
  src/platform_impl/orbital/mod.rs
  src/platform_impl/web/event.rs
  src/platform_impl/web/event_loop/mod.rs
  src/platform_impl/web/event_loop/runner.rs
  src/platform_impl/web/event_loop/window_target.rs
  src/platform_impl/web/web_sys/canvas.rs
  src/platform_impl/web/web_sys/pointer.rs
  src/platform_impl/web/window.rs
  src/platform_impl/windows/event_loop.rs
  src/platform_impl/windows/mod.rs
  src/window.rs
Labels: S - api, S - platform parity
