Repository rust-windowing/winit, pull requests merged in 2024-04, with the labels that each got.

#3620 Fix CI failing when updating `typos` to 1.20.3
  src/platform_impl/linux/x11/ime/input_method.rs
  typos.toml
Labels: S - maintenance, B - build failure

#3624 wayland: bump sctk-adwaita to 0.9.0
  Cargo.toml
  src/changelog/unreleased.md
Labels: DS - wayland

#3622 More concise `Debug` output for `WindowId`.
  src/changelog/unreleased.md
  src/window.rs
Labels: S - enhancement

#3607 Forked version of "Rework CONTRIBUTING guidelines" without controversial changes
  CONTRIBUTING.md
Labels: C - nominated

#3640 Fix icrate's clippy customization
  clippy.toml
Labels: DS - macos, DS - ios, S - maintenance

#3637 Re-introduce Web examples
  .cargo/config.toml
  Cargo.toml
  examples/control_flow.rs
  examples/util/tracing.rs
  examples/window.rs
  run-wasm/Cargo.toml
  run-wasm/src/main.rs
Labels: DS - web

#3625 wayland: fix CSD decorations glitch when closing
  src/changelog/unreleased.md
  src/platform_impl/linux/wayland/window/state.rs
Labels: DS - wayland

#3623 Windows: implement resize increments
  FEATURES.md
  src/changelog/unreleased.md
  src/platform_impl/windows/event_loop.rs
  src/platform_impl/windows/window.rs
  src/platform_impl/windows/window_state.rs
  src/window.rs
Labels: DS - windows

#3636 bugfix(android): Allow `Volume*` keys to be passed to the user
  src/changelog/unreleased.md
  src/platform_impl/android/mod.rs
Labels: DS - android

#3652 Fix a small error in the formatting
  .git-blame-ignore-revs
  src/event.rs
Labels: S - maintenance

#3593 On Windows, only return the window handle if it is on the correct thread
  src/changelog/unreleased.md
  src/platform/windows.rs
  src/platform_impl/windows/window.rs
Labels: DS - windows

#3657 Don't set the background color when initializing with transparency
  Cargo.toml
  src/changelog/unreleased.md
  src/platform_impl/macos/window_delegate.rs
  src/window.rs
Labels: B - bug, DS - macos

#3597 Add UIGestureRecognizerDelegate and PanGestureRecogniser plus default…
  examples/window.rs
  src/changelog/unreleased.md
  src/event.rs
  src/platform/ios.rs
  src/platform_impl/ios/uikit/gesture_recognizer.rs
  src/platform_impl/ios/uikit/mod.rs
  src/platform_impl/ios/view.rs
  src/platform_impl/ios/window.rs
Labels: DS - ios
