Repository rust-windowing/winit, pull requests merged in 2025-05, with the labels that each got.

#4217 Bump MSRV to 1.80
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  src/changelog/unreleased.md
  src/platform_impl/linux/common/xkb/mod.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/windows/dark_mode.rs
  src/platform_impl/windows/event_loop.rs
  src/platform_impl/windows/keyboard_layout.rs
  src/platform_impl/windows/util.rs
  src/utils.rs
Labels: S - maintenance

#4227 chose: Appease clippy
  clippy.toml
  examples/dnd.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/x11/util/randr.rs
  src/platform_impl/linux/x11/window.rs
Labels: S - maintenance

#4240 Use workspace dependencies everywhere
  Cargo.toml
  winit-core/Cargo.toml
Labels: S - maintenance

#4234 Update modifier state docs
  src/platform_impl/linux/common/xkb/state.rs
  winit-core/src/event.rs
  winit-core/src/keyboard.rs
Labels: S - docs

#4251 doc: add info on sticky vs toggle modifier behavior
  winit-core/src/keyboard.rs
Labels: S - docs

#4147 macOS: Remove panic wrapper
  src/platform_impl/apple/appkit/app_state.rs
  src/platform_impl/apple/appkit/event_loop.rs
  src/platform_impl/apple/appkit/observer.rs
Labels: DS - macos, S - maintenance

#4190 fix: Allow unknown bit-depth on macOS
  src/changelog/unreleased.md
  src/platform_impl/apple/appkit/ffi.rs
  src/platform_impl/apple/appkit/monitor.rs
  winit-core/src/monitor.rs
Labels: DS - macos, B - crash

#4250 Move Android backend to `winit-android`
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Cargo.toml
  src/event_loop.rs
  src/platform/mod.rs
  src/platform_impl/mod.rs
  winit-android/Cargo.toml
  winit-android/README.md
  winit-android/src/event_loop.rs
  winit-android/src/keycodes.rs
  winit-android/src/lib.rs
Labels: DS - android, S - maintenance

#4247 Move Windows backend to `winit-win32`
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Cargo.toml
  src/event_loop.rs
  src/platform/mod.rs
  src/platform_impl/mod.rs
  src/platform_impl/windows/mod.rs
  winit-win32/Cargo.toml
  winit-win32/README.md
  winit-win32/src/dark_mode.rs
  winit-win32/src/definitions.rs
  winit-win32/src/dpi.rs
  winit-win32/src/drop_handler.rs
  winit-win32/src/event_loop.rs
  winit-win32/src/event_loop/runner.rs
  winit-win32/src/icon.rs
  winit-win32/src/ime.rs
  winit-win32/src/keyboard.rs
  winit-win32/src/keyboard_layout.rs
  winit-win32/src/lib.rs
  winit-win32/src/minimal_ime.rs
  winit-win32/src/monitor.rs
  winit-win32/src/raw_input.rs
  winit-win32/src/util.rs
  winit-win32/src/window.rs
  winit-win32/src/window_state.rs
Labels: DS - windows, S - maintenance

#4241 Move shared code to new crate `winit-common`
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Cargo.toml
  src/platform_impl/apple/appkit/app_state.rs
  src/platform_impl/apple/appkit/event_loop.rs
  src/platform_impl/apple/appkit/mod.rs
  src/platform_impl/apple/appkit/notification_center.rs
  src/platform_impl/apple/mod.rs
  src/platform_impl/apple/uikit/app_state.rs
  src/platform_impl/apple/uikit/event_loop.rs
  src/platform_impl/apple/uikit/mod.rs
  src/platform_impl/apple/uikit/notification_center.rs
  src/platform_impl/linux/common/mod.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/seat/keyboard/mod.rs
  src/platform_impl/linux/wayland/window/mod.rs
  src/platform_impl/linux/x11/event_processor.rs
  src/platform_impl/linux/x11/mod.rs
  src/platform_impl/linux/x11/window.rs
  winit-common/Cargo.toml
  winit-common/README.md
  winit-common/src/core_foundation/event_loop_proxy.rs
  winit-common/src/core_foundation/mod.rs
  winit-common/src/event_handler.rs
  winit-common/src/lib.rs
  winit-common/src/xkb/compose.rs
  winit-common/src/xkb/keymap.rs
  winit-common/src/xkb/mod.rs
  winit-common/src/xkb/state.rs
Labels: DS - macos, DS - x11, DS - wayland, DS - ios, S - maintenance

#4242 Split UIKit backend out into `winit-uikit`
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Cargo.toml
  src/platform/mod.rs
  src/platform_impl/apple/mod.rs
  src/platform_impl/apple/uikit/mod.rs
  src/platform_impl/apple/uikit/notification_center.rs
  src/platform_impl/mod.rs
  winit-uikit/Cargo.toml
  winit-uikit/README.md
  winit-uikit/src/app_state.rs
  winit-uikit/src/event_loop.rs
  winit-uikit/src/lib.rs
  winit-uikit/src/monitor.rs
  winit-uikit/src/notification_center.rs
  winit-uikit/src/view.rs
  winit-uikit/src/view_controller.rs
  winit-uikit/src/window.rs
Labels: DS - ios, S - maintenance

#4252 Move Wayland backend to `winit-wayland`
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Cargo.toml
  src/event_loop.rs
  src/platform/mod.rs
  src/platform_impl/linux/mod.rs
  src/platform_impl/linux/wayland/mod.rs
  winit-wayland/Cargo.toml
  winit-wayland/README.md
  winit-wayland/src/event_loop/mod.rs
  winit-wayland/src/event_loop/proxy.rs
  winit-wayland/src/event_loop/sink.rs
  winit-wayland/src/lib.rs
  winit-wayland/src/output.rs
  winit-wayland/src/seat/keyboard/mod.rs
  winit-wayland/src/seat/mod.rs
  winit-wayland/src/seat/pointer/mod.rs
  winit-wayland/src/seat/pointer/relative_pointer.rs
  winit-wayland/src/seat/text_input/mod.rs
  winit-wayland/src/seat/touch/mod.rs
  winit-wayland/src/state.rs
  winit-wayland/src/types/cursor.rs
  winit-wayland/src/types/kwin_blur.rs
  winit-wayland/src/types/mod.rs
  winit-wayland/src/types/wp_fractional_scaling.rs
  winit-wayland/src/types/wp_viewporter.rs
  winit-wayland/src/types/xdg_activation.rs
  winit-wayland/src/window/mod.rs
  winit-wayland/src/window/state.rs
Labels: DS - wayland, S - maintenance

#4257 chore: Move event loop recreation check into backends themselves
  src/event_loop.rs
  src/platform_impl/web/event_loop/mod.rs
  src/platform_impl/web/event_loop/runner.rs
  winit-android/src/event_loop.rs
  winit-appkit/src/app_state.rs
  winit-appkit/src/event_loop.rs
  winit-core/src/error.rs
  winit-orbital/src/event_loop.rs
  winit-uikit/src/event_loop.rs
  winit-wayland/src/event_loop/mod.rs
  winit-win32/src/event_loop.rs
  winit-x11/src/event_loop.rs
Labels: S - maintenance
