Repository rust-windowing/winit, pull requests merged in 2025-01, with the labels that each got.

#4054 Modify child_window example
  examples/child_window.rs
  examples/util/fill.rs
Labels: S - docs

#4032 Use wrapper type for CFUUID
  src/platform_impl/apple/appkit/monitor.rs
Labels: B - bug, DS - macos

#4092 Update to `objc2` v0.6
  Cargo.toml
  src/changelog/unreleased.md
  src/platform/ios.rs
  src/platform/macos.rs
  src/platform_impl/apple/appkit/app.rs
  src/platform_impl/apple/appkit/app_state.rs
  src/platform_impl/apple/appkit/cursor.rs
  src/platform_impl/apple/appkit/event.rs
  src/platform_impl/apple/appkit/event_loop.rs
  src/platform_impl/apple/appkit/ffi.rs
  src/platform_impl/apple/appkit/menu.rs
  src/platform_impl/apple/appkit/monitor.rs
  src/platform_impl/apple/appkit/observer.rs
  src/platform_impl/apple/appkit/util.rs
  src/platform_impl/apple/appkit/view.rs
  src/platform_impl/apple/appkit/window.rs
  src/platform_impl/apple/appkit/window_delegate.rs
  src/platform_impl/apple/notification_center.rs
  src/platform_impl/apple/uikit/app_state.rs
  src/platform_impl/apple/uikit/event_loop.rs
  src/platform_impl/apple/uikit/monitor.rs
  src/platform_impl/apple/uikit/view.rs
  src/platform_impl/apple/uikit/view_controller.rs
  src/platform_impl/apple/uikit/window.rs
  src/platform_impl/linux/wayland/seat/pointer/mod.rs
Labels: DS - macos, DS - ios, S - maintenance, dependencies

#4105 Document that we require cargo +nightly fmt
  CONTRIBUTING.md
Labels: S - docs
